services:
  mongo-cars:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_car_data:/data/db

  mysql-bookings:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_booking_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-fleetinfo:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_fleetinfo_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  car-service:
    depends_on:
      - mongo-cars
    image: Enterprise-Rent-App/car-service
    ports:
      - 8080:8080
    links:
      - mongo-cars
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-cars

  inventory-service:
    depends_on:
      - mysql-fleetinfo
    image: Enterprise-Rent-App/fleet-service
    ports:
      - 8082:8082
    links:
      - mysql-fleetinfo
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-fleetinfo
      MYSQL_DB_PORT: 3307

  booking-service:
    depends_on:
      - car-service
      - fleet-service
    image: Enterprise-Rent-App/booking-service
    ports:
      - 8081:8081
    links:
      - car-service
      - fleet-service
    environment:
      CAR_SERVICE_BASEURL: car-service:8080
      INVENTORY_INFO_SERVICE_BASEURL: fleet-service:8082
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-bookings
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - car-service
      - booking-service
    image: Enterprise-Rent-App/api-gateway
    ports:
      - 8083:8083
    links:
      - car-service
      - booking-service
    environment:
      CAR_SERVICE_BASEURL: car-service:8080
      BOOKING_SERVICE_BASEURL: booking-service:8081

volumes:
  mongodb_car_data:
  mysql_fleetinfo_data:
  mysql_booking_data: