server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: car-service
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars
            - Method=POST
          filters:
            - SetPath=/api/car
        - id: car-service-get
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars
            - Method=GET
          filters:
            - SetPath=/api/car
        - id: car-service-all
          uri: http://${CAR_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/cars/all
            - Method=GET
          filters:
            - SetPath=/api/car/all
        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=POST
          filters:
            - SetPath=/api/booking
        - id: booking-service-get
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=GET
          filters:
            - SetPath=/api/booking
        - id: booking-service-all
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings/all
            - Method=GET
          filters:
            - SetPath=/api/booking/all
        - id: booking-service-put
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=PUT
          filters:
            - SetPath=/api/booking/update
        - id: booking-service-delete
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/bookings
            - Method=DELETE
          filters:
            - SetPath=/api/booking/delete